# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
env_variables:
  SQL_USER: root
  SQL_PASSWORD: 123456
  SQL_DATABASE: data
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: circular-source-174612:europe-west1:display-db
  SQL_CLIENT: mysql
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: circular-source-174612:europe-west1:display-db
# [END cloudsql_settings]
# [END app_yaml]